name: Check Docker Hub Connection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker image exists
        run: |
          # Проверяем существование образа без авторизации
          docker manifest inspect daygo555/device-os-libs:v1.0 > /dev/null && \
          echo "✅ Образ daygo555/device-os-libs:v1.0 существует!" || \
          echo "❌ Образ не найден!"